import {describe,it,expect,afterAll} from 'vitest';
import {db,getPool} from '@/lib/db';
import {MaterialInventory} from '@/lib/services/material-inventory';
import {InventoryRequests} from '@/lib/services/inventory-requests';
import {randomUUID} from 'node:crypto';
import {DeliveryGridService} from '@/lib/services/assurance-tickets/delivery-grid.service';
import {getProjectsService,getOperationsDatabase,getProjectAuditService,getStaffService,getServiceDeliveryService} from '@/lib/services/registry';
describe('Existing Supabase database (read only)',()=>{
 it('inventory requests validate, deduct batches atomically and deduplicate retries (rolled back)',async()=>{
  await expect(db.transaction(async tx=>{
   const connection={query:tx.query.bind(tx),transaction:async fn=>fn(tx)} as typeof db;
   const inventory=new MaterialInventory(connection),requests=new InventoryRequests(connection);
   const [project]=await tx.query("SELECT id FROM projects WHERE code='SERVICE_ASSURANCE'");
   const actor=randomUUID();
   const first=await inventory.create(project.id,{kind:'material',name:'Request rollback first',unit:'m'},actor);
   const second=await inventory.create(project.id,{kind:'material',name:'Request rollback second',unit:'pcs'},actor);
   for(const material of [first,second])await inventory.create(project.id,{kind:'opening',material_id:material.id,quantity:10,date:'2026-01-01',mutation_id:randomUUID()},actor);
   const payload={project_id:project.id,request_id:randomUUID(),items:[{material_id:first.id,quantity:2.1234},{material_id:second.id,quantity:3}]};
   await expect(requests.deduct({...payload,items:[payload.items[0],{material_id:second.id,quantity:1.5}]},actor)).rejects.toThrow('whole number');
   for(const kind of ['received','faulty','adjustment'])await expect(inventory.create(project.id,{kind,direction:'deduct',reference:'Test units',material_id:second.id,quantity:1.5,date:'2026-01-02',mutation_id:randomUUID()},actor)).rejects.toThrow('whole number');
   for(const quantity of [0,-1,NaN,Infinity,1.12345,'2'])await expect(requests.deduct({...payload,items:[{material_id:first.id,quantity}]},actor)).rejects.toThrow('Quantity');
   await expect(requests.deduct({...payload,project_id:randomUUID()},actor)).rejects.toThrow('Project');
   await expect(requests.deduct({...payload,items:[{material_id:randomUUID(),quantity:1}]},actor)).rejects.toThrow('does not belong');
   await expect(requests.deduct({...payload,items:[payload.items[0],payload.items[0]]},actor)).rejects.toThrow('only once');
   await expect(requests.deduct({...payload,items:[payload.items[0],{material_id:second.id,quantity:11}]},actor)).rejects.toThrow('Insufficient stock');
   expect((await requests.available(project.id)).find(r=>r.id===first.id).available).toBe(10);
   await requests.deduct(payload,actor);
   await requests.deduct(payload,actor);
   const available=await requests.available(project.id);
   expect(available.find(r=>r.id===first.id).available).toBe(7.8766);
   expect(available.find(r=>r.id===second.id).available).toBe(7);
   expect(await tx.query("SELECT id FROM inventory_entries WHERE reference=$1",[`inventory-request:${payload.request_id}`])).toHaveLength(2);
   await expect(requests.deduct({...payload,items:[{material_id:first.id,quantity:1}]},actor)).rejects.toThrow('already been used');
   await expect(requests.deduct(payload,randomUUID())).rejects.toThrow('already been used');
   await expect(requests.deduct({...payload,request_id:randomUUID(),items:[{material_id:second.id,quantity:8}]},actor)).rejects.toThrow('Insufficient stock');
   const [{month}]=await tx.query("SELECT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Bahrain','YYYY-MM') AS month");
   const report=await inventory.list(project.id,month);
   expect(report.requestHistory.filter(r=>r.reference===`inventory-request:${payload.request_id}`)).toHaveLength(2);
   const ownHistory=await requests.history(actor);
   expect(ownHistory).toHaveLength(2);
   expect(ownHistory.map(r=>Number(r.quantity)).sort()).toEqual([2.1234,3]);
   expect(await requests.history(randomUUID())).toEqual([]);
   throw new Error('request test rollback');
  })).rejects.toThrow('request test rollback');
 },60000);
 it('Phase 1 grid persists exact drafts and promotes safely without changing old records on invalid edits',async()=>{
  await expect(db.transaction(async tx=>{
   const service=new DeliveryGridService({query:tx.query.bind(tx),transaction:async fn=>fn(tx)} as typeof db);
   const [project]=await tx.query("SELECT id FROM projects WHERE code='SERVICE_ASSURANCE'");
   const [profile]=await tx.query("SELECT id FROM profiles WHERE role='controller' AND is_active LIMIT 1");
   const actor={userId:profile.id,role:'controller'},id=randomUUID();
   const raw={ticket_number:'00'+id,mobile:'001234',resolution_description:'  first\nsecond  ',work_date:'bad date',status:'Open'};
   let payload={id,project_id:project.id,values:raw,mutation_id:randomUUID(),draft_version:0,base_version:null as number|null};
   const first=await service.save(payload,actor);
   expect(first.draft.state).toBe('draft');expect(first.draft.raw_values.resolution_description).toBe(raw.resolution_description);
   expect(await tx.query('SELECT id FROM assurance_tickets WHERE id=$1',[id])).toHaveLength(0);
   const retry=await service.save(payload,actor);expect(retry.draft.version).toBe(first.draft.version);
   payload={...payload,values:{...raw,work_date:'02/10/2026'},mutation_id:randomUUID(),draft_version:first.draft.version};
   const second=await service.save(payload,actor);
   expect(second.draft.errors).toEqual({});expect(second.draft.state).toBe('record');expect(second.record.ticket_number).toBe(raw.ticket_number);
   expect(second.record.controller_id).toBe(actor.userId);expect(second.draft.raw_values.work_date).toBe('02/10/2026');
   const [other]=await tx.query("SELECT id FROM profiles WHERE role IN ('admin','controller') AND id<>$1 LIMIT 1",[actor.userId]);
   if(other)expect((await service.list(project.id,{userId:other.id,role:'controller'})).find(d=>d.id===id)?.raw_values.work_date).toBe('02/10/2026');
   await expect(service.save({...payload,mutation_id:randomUUID()},actor)).rejects.toThrow('another tab');
   const third=await service.save({...payload,values:{...raw,work_date:'still invalid'},draft_version:second.draft.version,base_version:second.record.version,mutation_id:randomUUID()},actor);
   expect(third.draft.state).toBe('draft');expect((await tx.query('SELECT version FROM assurance_tickets WHERE id=$1',[id]))[0].version).toBe(second.record.version);
   const fourth=await service.save({...payload,values:{...raw,work_date:'02/10/2026',creation_datetime:'02/10/2026 12:00',close_datetime:'02/10/2026 15:00',controller_id:randomUUID(),sla_from_creation:'900'},draft_version:third.draft.version,base_version:second.record.version,mutation_id:randomUUID()},actor);
   expect(fourth.draft.state).toBe('record');expect(Number(fourth.record.sla_from_creation)).toBe(0.125);expect(fourth.record.controller_id).toBe(actor.userId);
   await tx.query('UPDATE assurance_tickets SET version=version+1 WHERE id=$1',[id]);
   const conflict=await service.save({...payload,draft_version:fourth.draft.version,base_version:fourth.record.version,mutation_id:randomUUID()},actor);
   expect(conflict.draft.errors._row).toContain('changed elsewhere');expect(conflict.draft.raw_values.work_date).toBe('02/10/2026');
   throw new Error('grid test rollback');
  })).rejects.toThrow('grid test rollback');
 },60000);
 afterAll(async()=>{await getPool().end();});
 it('reads existing projects in the saved display sequence',async()=>{
  const service=await getProjectsService().findAll();
  const sql=await db.query('SELECT id FROM projects ORDER BY display_order,name,id');
  expect(service.map(p=>p.id)).toEqual(sql.map(p=>p.id));
 });
 it('rebuilds database-backed operational pages and audit after a cold start',async()=>{
  const [project]=await db.query("SELECT id FROM projects WHERE code='SERVICE_ASSURANCE'");
  const audit=await getProjectAuditService().run(project.id);
  const [count]=await db.query('SELECT count(*)::int n FROM assurance_tickets WHERE project_id=$1',[project.id]);
  expect(audit.verification).toHaveLength(count.n);
  expect((await getStaffService().getStats()).total).toBeGreaterThan(0);
  expect((await getServiceDeliveryService().getStatus()).responseRecordCount).toBeGreaterThan(0);
  const records=await getOperationsDatabase().delivery();
  expect(records.length).toBeGreaterThan(0);
 },60000);
 it('supports atomic multi-query transactions without persisting a test mutation',async()=>{
  await expect(db.transaction(async tx=>{await tx.query('SELECT 1');throw new Error('rollback probe')})).rejects.toThrow('rollback probe');
  expect((await db.query('SELECT 1 AS value'))[0].value).toBe(1);
 });
 it('carries inventory across months, deduplicates receipts and protects dated balances (rolled back)',async()=>{
  await expect(db.transaction(async tx=>{
   const service=new MaterialInventory({query:tx.query.bind(tx),transaction:async fn=>fn(tx)} as typeof db);
   const [project]=await tx.query("SELECT id FROM projects WHERE code='SERVICE_ASSURANCE'");
   const actor=randomUUID();
   const material=await service.create(project.id,{kind:'material',name:'Inventory rollback test',unit:'Meter'},actor);
   const add=(kind:string,date:string,quantity:number)=>({kind,date,quantity,material_id:material.id,mutation_id:randomUUID()});
   await service.create(project.id,add('opening','2026-07-01',100.125),actor);
   const receipt=add('received','2026-07-31',20);
   await service.create(project.id,receipt,actor);await service.create(project.id,receipt,actor);
   await service.create(project.id,add('faulty','2026-08-01',10),actor);
   let report=await service.list(project.id,'2026-07');
   expect(report.rows.find(r=>r.id===material.id)).toMatchObject({opening:100.125,received:20,used:0,faulty:0,remaining:120.125});
   report=await service.list(project.id,'2026-09');
   expect(report.rows.find(r=>r.id===material.id)).toMatchObject({opening:110.125,received:0,remaining:110.125});
   await expect(service.create(project.id,add('faulty','2026-07-15',115),actor)).rejects.toThrow('exceeds');
   await expect(service.create(project.id,add('received','2026-06-30',1),actor)).rejects.toThrow('precede');
   await expect(service.create(project.id,add('opening','2026-09-01',1),actor)).rejects.toThrow('first entry');
   await service.create(project.id,add('received','2026-10-01',5),actor);
   report=await service.list(project.id,'2026-09');
   expect(report.rows.find(r=>r.id===material.id).remaining).toBe(110.125);
   const correction={...add('adjustment','2026-09-05',2.125),direction:'deduct',reference:'Used elsewhere'};
   await expect(service.create(project.id,{...correction,reference:' '},actor)).rejects.toThrow('reference');
   await expect(service.create(project.id,{...correction,direction:'other'},actor)).rejects.toThrow('add or deduct');
   await expect(service.create(project.id,{...correction,quantity:111},actor)).rejects.toThrow('exceeds');
   await service.create(project.id,correction,actor);
   await service.create(project.id,correction,actor);
   await service.create(project.id,{...correction,mutation_id:randomUUID(),direction:'add',quantity:1,reference:'Quantity correction'},actor);
   report=await service.list(project.id,'2026-09');
   expect(report.rows.find(r=>r.id===material.id)).toMatchObject({used:2.125,received:1,remaining:109});
   expect(report.history.filter(r=>r.reference.startsWith('Stock correction:'))).toHaveLength(2);
   expect((await tx.query('SELECT actor_id FROM inventory_entries WHERE mutation_id=$1',[correction.mutation_id]))[0].actor_id).toBe(actor);
   throw new Error('inventory rollback complete');
  })).rejects.toThrow('inventory rollback complete');
 },60000);
});
